/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "wood": "原木",
    "stone": "圆石",
    "blood": "血",
    "blood magic": "血魔法",
    "attack": "攻击",
    "copper": "铜",
    "coal": "煤",
    "iron": "铁",
    "“kill it” Extra give Blood": "“杀死它”格外获得血",
    "A good rest makes it easier for you to dig stones": "好好休息让你更好的挖石头",
    "A wooden house can make you better fight(ATK best + 1": "一个木屋可以帮助你更好的战斗(攻击力底数+1",
    "No wood in the mine": "在矿洞里没有木头",
    "No wood in the mine2.0": "在矿洞里没有木头2.0",
    "No wood in the mine3.0": "在矿洞里没有木头3.0",
    "No wood in the mine4.0": "在矿洞里没有木头4.0",
    "Reset for +": "重置获得 +",
    "Stone house": "石屋",
    "stone!": "石头!",
    "This makes you negative, the Time acquisition is only 45%, the Wood base is *4": "这使你消极,时间获取只有45%,原木获取底数*4",
    "This makes you negative, the Time acquisition is only 55%, the Wood base is *3": "这使你消极,时间获取只有55%,原木获取底数*4",
    "This makes you negative, the Time acquisition is only 65%, the Wood base is *2": "这使你消极,时间获取只有65%,原木获取底数*4",
    "This makes you negative, the Time acquisition is only 75": "这使你消极,时间获取只有75",
    "Unlock a new challenge & wood consumption divided by 1.5": "解锁一个新挑战并且原木获得指数*1.5",
    "axe": "斧子",
    "Completed": "完成",
    "Compression technology": "压缩技术",
    "Fire prevention, It’s also a solid defense(ATK best +1": "防火,也是坚固的防御(攻击力底数+1",
    "Get 1% wood every second": "每秒获得1%的原木",
    "Make stone_axe (Improve wood acquisition": "制作石斧(木头获取更好",
    "Many axes": "许多斧子",
    "Unlock a new wood upgrade": "解锁1个新升级",
    "Unlock three new rows": "解锁3个新层",
    "Unlock two new wood upgrade": "解锁2个新升级",
    "You can compress your stone(画大饼": "你可以压缩你的圆石(画大饼",
    "You got stone, which makes you feel excited, you want to spend more time playing this game (Time acquisition is 200": "你得到了圆石，这让你感到兴奋，你想花更多的时间玩这个游戏（时间获取变成200",
    "1stone": "1圆石",
    "20 wood": "20 原木",
    "35 wood": "35 原木",
    "60 wood": "60 原木",
    "Exit Early": "进行中",
	"Finish": "结束",
	"10000wood -> 7000$": "10000原木 -> 7000$",
	"25wood -> 13$": "25原木 -> 13$",
	"5wood -> 2$": "5原木 -> 2$",
	"Backpack, inventory, hands are all wood": "背包,物品栏,手全是原木",
	"big wood bed": "大木床",
	"Buy and sell": "买和卖",
	"Charcoal": "木炭",
	"coal and charcoal?(unlock coal upgrade": "煤炭和木炭?(解锁煤炭升级",
	"Crafts": "工艺品",
	"Current endgame: 1 iron": "当前残局:1铁",
	"Currently": "目前",
	"Demon": "恶魔",
	"Each wood upgrade will increase the production Time by 0.05 times": "每个原木升级将提升0.05倍的时间",
	"fast!": "快!",
	"Hidden Achievements": "隐藏成就",
	"keep wood upgrade": "保留原木升级",
	"Make wooden_pickaxe": "制作木镐",
	"Only used three times": "只用三次",
	"Planks": "木板",
	"Really too much!": "真的太多了!",
	"Soon": "快了",
	"Strengthen “wood!”": "提升“原木!”",
	"Strengthen “wood” & “The Game Tree is AWESOME!”": "提升“原木!”和“游戏树太棒了!(强调)”",
	"The End?": "结束了?",
	"The Game Tree is AWESOME!": "游戏树太棒了!(强调)",
	"The upgrade effect in the left and right directions is increased by the power of 0.07": "左右升级效果指数+0.07",
	"time": "时间",
	"too much!": "太多了!",
	"too too much!": "太多太多了!",
	"V is Virtual | R is Reality": "V 代表虚拟 | R 代表真实",
	"With real money": "用真钱",
	"wood requires -1": "原木获取底数-1",
	"wood!": "原木!",
	"wooden_axe": "木斧",
	"You can sell your woods": "你可以卖掉你的原木",
	"You can sell your woods, but more cost-effective": "你可以卖掉你的原木,但是效果更好",
	"You got wood, which makes you feel excited, you want to spend more time playing this game": "你有了原木，这让你感到兴奋，你想花更多的时间玩这个游戏",
	"Enough!": "够多了!",
	"yeeeeeeeee": "恶臭",
	"you find 1 Hidden Achievements": "你找了了1个隐藏成就",
	"you find 2 Hidden Achievements": "你找了了2个隐藏成就",
	"you find 3 Hidden Achievements": "你找了了3个隐藏成就",
	"you find 4 Hidden Achievements": "你找了了4个隐藏成就",
	"you find 5 Hidden Achievements": "你找了了5个隐藏成就",
	"you find 6 Hidden Achievements": "你找了了6个隐藏成就",
	"you find 7 Hidden Achievements": "你找了了7个隐藏成就",
	"you find 8 Hidden Achievements": "你找了了8个隐藏成就",
	"have 2368 wood in s 22challenge": "在圆石挑战22中获得2368木头",
	"have 666 blood": "拥有666血",
	"And no demons": "并没有恶魔",
	"Achievement Gotten!": "获得成就!",
	"have 114514 wood": "拥有114514原木",
	"Is it necessary to take such a foul-smelling achievement?": "有必要拿这么臭的成就吗？",
	"ATK best gained based on blood increase": "更具血增加攻击力底数",
	"Blood copper": "血铜",
	"Blood stone": "血石",
	"Blood wood": "血木",
	"Blood, blood, I need blood. OH!,I still need an altar": "血,血,我需要血.哦!我还需要一个祭坛",
	"Coal merchant": "煤商",
	"Efficiency Rune I": "效率符文I",
	"Efficiency Rune II": "效率符文II",
	"Endurance Rune I": "力量符文I",
	"Endurance Rune II": "力量符文II",
	"Get extra “kill it”": "获得格外的“杀死它!”",
	"keep s challenge": "保留圆石挑战",
	"Light up here": "照亮这里",
	"Light up here.": "照亮这里.",
	"Magic?": "魔法?",
	"make torch(1coal + 1000wood = 4torch": "制作火把(1煤炭 + 1000原木 = 4火把",
	"Next at NaN time": "无法获得下一个",
	"No wood but have torches": "没有原木但有火把",
	"No wood in the mine. but have ore": "在矿洞里没有木头,但是有矿",
	"No wood in the mine. but have ore2.0": "在矿洞里没有木头,但是有矿2.0",
	"No wood in the mine.but...": "在矿洞里没有木头.但是...",
	"No zombies will bother you logging.(get 9% wood every second": "没有僵尸会打扰你砍树.(每秒获得 9% 的原木",
	"Sell and buy ​​some coal": "买和卖一些煤",
	"Torch": "火把",
	"unlock c challenge": "解锁煤炭挑战",
	"Unlock c upgrade, coal best - 5.": "解锁煤炭升级,煤炭底数-5",
	"Unlock s upgrade, stone best - 2.": "解锁圆石升级,煤炭底数-2",
	"you find coal, the Time acquisition is only 40%, the stone best * 3.5": "你找到了煤,时间获取只有40%,圆石获取底数*3.5",
	"you find stone, the Time acquisition is only 50%, the stone best * 3": "你找到了圆石,时间获取只有50%,圆石获取底数*3",
	"30 stone": "30圆石",
	"75 stone": "75圆石",
	"Play games by slowing down": "通过减速玩游戏",
	"Play games by speeding up": "通过加速玩游戏",
	"st.OH!You go on.": "停.哦!你继续",
	"stop!!!": "停下!!!",
	"The pinnacle of immorality": "不道德的巅峰",
	"The pinnacle of morality": "道德的巅峰",
	"Make copper_axe(unlock two upgrades": "制作铜斧(解锁2个升级",
	"Make copper_pickaxe(stone requires -5": "制作铜镐(圆石底数 -5",
	"copper_axe": "铜斧",
	"copper_pickaxe": "铜镐",
	"100 ATK": "100攻击力",
	"1000 ATK": "1000攻击力",
	"10000 ATK": "10000攻击力",
	"100000 ATK": "100000攻击力",
	"1000000 ATK": "1000000攻击力",
	"0.1% get copper": "0.1%获得铜",
	"1% get copper": "1%获得铜",
	"10% get copper": "10%获得铜",
	"100% get copper": "100%获得铜",
	"1000% get copper": "1000%获得铜",
	"get 0~1000 blood": "获得0~1000血",
	"get 0~10000 blood": "获得0~10000血",
	"get 0~100000 blood": "获得0~100000血",
	"get 0~1000000 blood": "获得0~1000000血",
	"get 0~10000000 blood": "获得0~10000000血",
	"kill it! *1": "杀死它! *1",
	"kill it! *10": "杀死它! *10",
	"kill it! *100": "杀死它! *100",
	"kill it! *1000": "杀死它! *1000",
	"kill it! *10000": "杀死它! *10000",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '\t\t\t\tGoal:': '需求:',
    '\t\t\t\tReward': '奖励:',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Currently：": "效果：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$wood/,
    /^[\u4E00-\u9FA5]+$/,

];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Cost: (\d+) wood/, '成本：$1 原木'],
	[/^Cost: (\d+) torch/, '成本：$1 火把'],
	[/^Cost: ([\d\.,]+) wood/, '成本：$1 原木'],
	[/^Cost: (\d+) stone/, '成本：$1 圆石'],
	[/^Cost: (\d+) coal/, '成本：$1 煤炭'],
	[/^Cost: (\d+) blood magic/, '成本：$1 血魔法'],
	[/^Cost: (\d+) blood/, '成本：$1 血'],
	[/^Cost: ([\d\.,]+) blood/, '成本：$1 血'],
	[/^Cost: (\d+) copper/, '成本：$1 铜'],
	[/^Cost: (\d+) \$/, '成本：$1 $'],
	[/^Next at ([\d\.]+) copper/, '下一个 $1 铜']
]);