/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "wood": "原木",
    "stone": "圆石",
    "blood": "血",
    "blood magic": "血魔法",
    "attack": "攻击",
    "copper": "铜",
    "coal": "煤",
    "iron": "铁",
    "“kill it” Extra give Blood": "“杀死它”格外获得血",
    "A good rest makes it easier for you to dig stones": "好好休息让你更好的挖石头",
    "A wooden house can make you better fight(ATK base + 1": "一个木屋可以帮助你更好的战斗(攻击力底数+1",
    "No wood in the mine": "在矿洞里没有木头",
    "No wood in the mine2.0": "在矿洞里没有木头2.0",
    "No wood in the mine3.0": "在矿洞里没有木头3.0",
    "No wood in the mine4.0": "在矿洞里没有木头4.0",
    "Reset for +": "重置获得 +",
    "Stone house": "石屋",
    "stone!": "圆石!",
    "This makes you negative, the Time acquisition is only 50%, the Wood base is *4": "这使你消极,时间获取只有50%,原木获取底数*4",
    "This makes you negative, the Time acquisition is only 60%, the Wood base is *3": "这使你消极,时间获取只有60%,原木获取底数*3",
    "This makes you negative, the Time acquisition is only 70%, the Wood base is *2": "这使你消极,时间获取只有70%,原木获取底数*2",
    "This makes you negative, the Time acquisition is only 80": "这使你消极,时间获取只有80",
    "Unlock a new challenge & wood consumption divided by 1.5": "解锁一个新挑战并且原木获得指数*1.5",
    "axe": "斧子",
    "Completed": "完成",
    "Compression technology": "压缩技术",
    "Fire prevention, It's also a solid defense(ATK base +1": "防火,也是坚固的防御(攻击力底数+1",
    "Get 1% wood every second": "每秒获得1%的原木",
    "Make stone_axe (Improve wood acquisition": "制作石斧(木头获取更好",
    "Many axes": "许多斧子",
    "Unlock three new rows": "解锁3个新层",
    "Unlock two new wood upgrade": "解锁2个新升级",
    "You can compress your stone(画大饼": "你可以压缩你的圆石(画大饼",
    "You got stone, which makes you feel excited, you want to spend more time playing this game (Time acquisition is 250": "你得到了圆石，这让你感到兴奋，你想花更多的时间玩这个游戏（时间获取变成250",
    "1stone": "1圆石",
    "20 wood": "20 原木",
    "35 wood": "35 原木",
    "60 wood": "60 原木",
	"Start": "开始",
    "Exit Early": "进行中",
	"Finish": "结束",
	"10000wood -> 7000$": "10000原木 -> 7000$",
	"25wood -> 13$": "25原木 -> 13$",
	"5wood -> 2$": "5原木 -> 2$",
	"Backpack, inventory, hands are all wood": "背包,物品栏,手全是原木",
	"big wood bed": "大木床",
	"Buy and sell": "买和卖",
	"Charcoal": "木炭",
	"coal and charcoal?(unlock coal upgrade & coal best - 3": "煤炭和木炭?(解锁煤炭升级并且煤炭底数-3",
	"Crafts": "工艺品",
	"Current endgame: 1 iron": "当前残局:1铁",
	"Currently": "目前",
	"Demon": "恶魔",
	"Each wood upgrade will increase the production Time by 0.05 times": "每个原木升级将提升0.05倍的时间",
	"fast!": "快!",
	"Hidden Achievements": "隐藏成就",
	"keep wood upgrade": "保留原木升级",
	"Make wooden_pickaxe": "制作木镐",
	"Only used three times": "只用三次",
	"Planks": "木板",
	"Really too much!": "真的太多了!",
	"Soon": "快了",
	"Strengthen “wood!”": "原木提升“原木!”",
	"Strengthen “wood” & “The Game Tree is AWESOME!”": "原木提升“原木!”和“游戏树太棒了!(强调)”",
	"The End?": "结束了?",
	"The Game Tree is AWESOME!": "游戏树太棒了!(强调)",
	"The upgrade effect in the left and right directions is increased by the power of 0.07": "左右升级效果指数+0.07",
	"time": "时间",
	"too much!": "太多了!",
	"too too much!": "太多太多了!",
	"With money": "用钱",
	"wood requires -1": "原木获取底数-1",
	"wood!": "原木!",
	"wooden_axe": "木斧",
	"You can sell your woods": "你可以卖掉你的原木",
	"You can sell your woods, but more cost-effective": "你可以卖掉你的原木,但是效果更好",
	"You got wood, which makes you feel excited, you want to spend more time playing this game": "你有了原木，这让你感到兴奋，你想花更多的时间玩这个游戏",
	"Enough!": "够多了!",
	"yeeeeeeeee": "恶臭",
	"you find 0 Hidden Achievements": "你找了了0个隐藏成就",
	"you find 1 Hidden Achievements": "你找了了1个隐藏成就",
	"you find 2 Hidden Achievements": "你找了了2个隐藏成就",
	"you find 3 Hidden Achievements": "你找了了3个隐藏成就",
	"you find 4 Hidden Achievements": "你找了了4个隐藏成就",
	"you find 5 Hidden Achievements": "你找了了5个隐藏成就",
	"you find 6 Hidden Achievements": "你找了了6个隐藏成就",
	"you find 7 Hidden Achievements": "你找了了7个隐藏成就",
	"you find 8 Hidden Achievements": "你找了了8个隐藏成就",
	"have 2368 Wood in s 22challenge": "在圆石挑战22中获得2368木头",
	"have 666 Blood": "拥有666血",
	"And no demons": "并没有恶魔",
	"Achievement Gotten!": "获得成就!",
	"have 114514 Wood": "拥有114514原木",
	"Is it necessary to take such a foul-smelling achievement?": "有必要拿这么臭的成就吗？",
	"ATK base gained based on blood increase": "根据血增加攻击力底数",
	"Blood copper": "血铜",
	"Blood stone": "血石",
	"Blood wood": "血木",
	"Blood, Blood, I need blood. OH!,I still need an altar": "血,血,我需要血.哦!我还需要一个祭坛",
	"Coal merchant": "煤商",
	"Efficiency Rune I": "效率符文I",
	"Efficiency Rune II": "效率符文II",
	"Endurance Rune I": "耐力符文I",
	"Endurance Rune II": "耐力符文II",
	"Get extra “kill it”": "获得格外的“杀死它!”",
	"keep s challenge": "保留圆石挑战",
	"Light up here.": "照亮这里.",
	"Light up there":"照亮那里",
	"wood base - 1":"原木获取 - 1",
	"Magic?": "魔法?",
	"make torch(1coal + 1000wood = 4torch": "制作火把(1煤炭 + 1000原木 = 4火把",
	"Next at NaN time": "无法获得下一个",
	"No wood but have torches": "没有原木但有火把",
	"No wood in the mine. but have ore": "在矿洞里没有木头,但是有矿",
	"No wood in the mine. but have ore2.0": "在矿洞里没有木头,但是有矿2.0",
	"No wood in the mine.but...": "在矿洞里没有木头.但是...",
	"No zombies will bother you logging.(Get 9% wood every second": "没有僵尸会打扰你砍树.(每秒获得 9% 的原木",
	"Sell and buy ​​some coal": "买和卖一些煤",
	"Torch": "火把",
	"unlock c challenge": "解锁煤炭挑战",
	"Unlock c upgrade, coal best - 5.": "解锁煤炭升级,煤炭底数-5",
	"Unlock s upgrade, stone best - 2.": "解锁圆石升级,煤炭底数-2",
	"you find coal, the Time acquisition is only 40%, the stone best * 3.5": "你找到了煤,时间获取只有40%,圆石获取底数*3.5",
	"you find stone, the Time acquisition is only 50%, the stone best * 3": "你找到了圆石,时间获取只有50%,圆石获取底数*3",
	"30 stone": "30圆石",
	"75 stone": "75圆石",
	"Play games by slowing down": "通过减速玩游戏",
	"Play games by speeding up": "通过加速玩游戏",
	"st.OH!You go on.": "停.哦!你继续",
	"stop!!!": "停下!!!",
	"The pinnacle of immorality": "不道德的巅峰",
	"The pinnacle of morality": "道德的巅峰",
	"Make copper_axe(unlock two upgrades": "制作铜斧(解锁2个升级",
	"Make copper_pickaxe(stone requires -5": "制作铜镐(圆石底数 -5",
	"copper_axe": "铜斧",
	"copper_pickaxe": "铜镐",
	"100 ATK": "100攻击力",
	"1000 ATK": "1000攻击力",
	"10000 ATK": "10000攻击力",
	"100000 ATK": "100000攻击力",
	"1000000 ATK": "1000000攻击力",
	"0.2% get Copper": "0.2%获得铜",
	"2% get Copper": "2%获得铜",
	"20% get Copper": "20%获得铜",
	"200% get Copper": "200%获得铜",
	"2000% get Copper": "2000%获得铜",
	"Get 0~1000 Blood": "获得0~1000血",
	"Get 0~10000 Blood": "获得0~10000血",
	"Get 0~100000 Blood": "获得0~100000血",
	"Get 0~1000000 Blood": "获得0~1000000血",
	"Get 0~10000000 Blood": "获得0~10000000血",
	"kill it! *1": "杀死它! *1",
	"kill it! *10": "杀死它! *10",
	"kill it! *100": "杀死它! *100",
	"kill it! *1000": "杀死它! *1000",
	"kill it! *10000": "杀死它! *10000",
	"Adrenaline": "肾上腺素",
	"Don't sleep in hell!": "不要在地狱里睡觉",
	"Get 5% $ every second": "每秒获得5%的$",
	"Investment is risky": "投资有风险",
	"3$ -> 5wood": "3$ -> 5原木",
	"30$ -> 50wood": "30$ -> 50原木",
	"500$ -> 5stone": "500$ -> 5圆石",
	"5000$ -> 1coal": "5000$ -> 1煤炭",
	"start": "开始",
	"too much?": "太多了?",
	"You can buy a new bed to Improve sleep quality (sleep time 9 hours> 6 hours).": "你可以买一张新床提高睡眠质量 (睡眠时长 9小时>6小时)",
	"You can buy some adrenalines to Improve sleep quality (sleep time 6 hours> 3 hours).": "你买一些肾上腺素提高睡眠质量 (睡眠时长 6小时>3小时)",
	"You can buy some coffee to stay up late to play The Game Tree (sleep time 12 hours> 9 hours).": "你可以买一些咖啡睡眠质量 (睡眠时长 12小时>9小时)",
	"You can buy some woods": "你可以买一些原木",
	"You can unlock a milestone": "你可以解锁一个里程碑",
	"You found a free idle game": "你发现一款免费的放置游戏",
	"Reduce the number of blood attack to get the base": "降低攻击获得底数",
	"Reduce the number of blood magic to get the base": "减少血魔法获取底数",
	"Speed Rune I": "速度符文I",
	"Speed Rune II": "速度符文II",
	"Strength Rune I": "力量符文I",
	"Strength Rune II": "力量符文II",
	"Immortal": "不朽",
	"Increase": "增加",
	"Keep blood on buyables & upgrade": "保留血符文和血升级",
	"No,no,no. But maybe I can make some blood runes": "不,不,不.但是我可以制作一些血符文",
	"soak": "浸泡",
	"Soak copper in blood, unlock copper upgrade": "把铜浸泡在血里,解锁铜升级",
	"Soak more more resources": "浸泡更多更多资源",
	"Soak more resources": "浸泡更多资源",
	"Soak stone in blood, The blood will corrode the stone part": "把圆石浸泡在血里,这将腐蚀掉圆石部分",
	"Soak wood in blood, unlock wood upgrade": "把原木浸泡在血里,解锁原木升级",
	"Soak your resources in blood": "在血里浸泡你的资源",
	"Time gained based on blood increase": "根据血提升时间基础生产",
	"Time gained based on blood magic increase": "根据血魔法提升时间基础生产",
	"Unlock Efficiency Rune I": "解锁效率符文I",
	"Unlock Efficiency Rune II": "解锁效率符文II",
	"Unlock Endurance Rune I": "解锁耐力符文I",
	"Unlock Speed Rune I": "解锁速度符文I",
	"Unlock more BM upgrades": "解锁更多血魔法升级",
	"Unlock Strength Rune I": "解锁力量符文I",
	"Drink?": "喝?",
	"expand": "扩大",
	"Milestone Gotten!": "获得里程碑",
	"you find stone, the Time acquisition is only 80%, the stone base * 2.5": "你找到了石头,时间获取只有80%,石头底数*2.5",
	"No wood in the mine. but have ore3.0": "在矿洞里没有木头,但是有矿3.0",
	"you find coal, the Time acquisition is only 40%, the stone base * 3.5": "你找到了煤炭,时间获取只有40%,石头底数*3.5",
	"you find copper, the Time acquisition is only 30%, the stone base * 4": "你找到了铜,时间获取只有30%,石头底数*4",
	"Unlock Battery,coal base - 4.": "解锁电池,煤炭底数-4",
	"Unlock c upgrade,coal base - 2.": "解锁煤升级,煤炭底数-2",
	"Unlock s upgrade,stone base - 1.": "解锁圆石升级,煤炭底数-1",
	"Make copper_pickaxe(stone requires -3": "制作铜镐(石头需求-3",
	"“stone!”can be strengthened with the increase of stones": "“圆石!”可以通过圆石获得加强",
	"What's so exciting about this?": "这有什么好激动的?",
	"Unlock a new wood upgrade & stone milestone": "解锁一个新原木升级和圆石里程碑",
	"You are not the only one to play": "并不是你一个人在玩",
	"5stone": "5圆石",
	"Keep wood upgrade": "保留原木升级",
	"ATK base gained based on Time increase": "根据时间增加攻击力底数",
	"1torch": "1火把",
	"keep s upgrades": "保留圆石升级",
	"magic wood": "魔法木",
	"blood magic and wood increase time production together": "血魔法和木头一起提升时间生产",
	"25torch": "25火把",
	"keep s milestones": "保留圆石里程碑",
	"matches?": "火柴?",
	"Torch making is more efficient": "火把制作效果更好",
	"Rubble": "碎石",
	"Collect excess rubble.(Each piece of coal will increase the stone index by 0.005, up to 0.25": "收集多余的碎石,可以让你更容易获得石头.(每块煤会使石头指数降低0.005,最高为0.25",
	"125torch": "125火把",
	"keep s challenges": "保留圆石挑战",
	"make torch(1coal + 800wood = 6torch": "制作火把(1煤炭 + 800原木 = 6火把",
	"You have dug": "你挖了",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '\t\t\t\tGoal:': '需求:',
    '\t\t\t\tReward': '奖励:',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Currently：": "效果：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$\$/,
	/^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/,

];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
	[/^Cost: (\d+) torch/, '成本：$1 火把'],
	[/^Cost: ([\d\.,]+) wood/, '成本：$1 原木'],
	[/^Cost: (\d+) stone/, '成本：$1 圆石'],
	[/^Cost: (\d+) coal/, '成本：$1 煤炭'],
	[/^Cost: ([\d\.,]+) blood magic/, '成本：$1 血魔法'],
	[/^Cost: ([\d\.,]+) blood/, '成本：$1 血'],
	[/^cost:([\d\.,]+)/, '成本:$1'],
	[/^Cost: (\d+) copper/, '成本：$1 铜'],
	[/^Cost: (\d+) \$/, '成本：$1 $'],
	[/^Next at ([\d\.,]+) copper/, '下一个 $1 铜'],
	[/^Next at ([\d\.,]+) time/, '下一个 $1 时间'],
	[/^Next at ([\d\.,]+) wood/, '下一个 $1 木头'],
	[/^Next at ([\d\.,]+) stone/, '下一个 $1 圆石'],
	[/^You have ([\d\.,]+) time/, '你有 $1 时间'],
	[/^You have ([\d\.,]+) wood/, '你有 $1 木头'],
	[/^You have ([\d\.,]+) ATK/, '你有 $1 攻击力'],
	[/^You have ([\d\.,]+) torch/, '你有 $1 火把'],
	[/^You have ([\d\.,]+) stone/, '你有 $1 圆石'],
	[/^You have ([\d\.,]+) blood magic/, '你有 $1 血魔法'],
	[/^You have ([\d\.,]+) blood/, '你有 $1 血'],
	[/^You have ([\d\.,]+) depth/, '你有 $1 深度'],
	[/^You get ([\d\.,]+)\/sec/, '你每秒获得 $1'],
	[/^Req: ([\d\.,]+) \/ ([\d\.,]+) stone/, '需求: $1 / $2 圆石'],
	[/^Dev Speed: ([\d\.,]+)x/, '时间加速$1x'],
	[/^Reach ([\d\.,]+) blood to unlock \(\You have ([\d\.,]+) blood/, '到达 $1 血以解锁(你有 $2 血'],
	[/([\d\.,]+) wood/, '$1 木头'],
	[/([\d\.,]+) stone/, '$1 圆石'],
	[/([\d\.,]+) blood magic/, '$1 血魔法'],
	[/([\d\.,]+) blood/, '$1 血'],
	[/([\d\.,]+) copper/, '$1 铜'],
	[/([\d\.,]+) coal/, '$1 煤炭'],
	[/([\d\.,]+) attack/, '$1 攻击'],
	[/([\d\.,]+) depth/, '$1 深度'],
	[/^Currently:\+([\d\.,]+) “kill it”/, '效果:+$1”杀死它“'],
	[/^Currently:\+([\d\.,]+) BM upgrades/, '效果:+$1血魔法升级'],
	[/^Currently:-([\d\.,]+)x/, '效果:-$1x'],
	[/^Currently:-([\d\.,]+)/, '效果:-$1'],
	[/^Currently:\+([\d\.,]+)x/, '效果:+$1x'],
	[/^Currently:\+([\d\.,]+)/, '效果:+$1'],
	[/^Currently:([\d\.,]+)x/, '效果:$1x'],
	[/^You have ([\d\.,]+)\/([\d\.,]+) electricity/, '你有 $1/$2 能量'],
]); 
